---
version: "3"

volumes:
  summers_api_local_postgres_data: {}
  summers_api_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: summers_api_local_django
    container_name: summers_api_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: summers_api_production_postgres
    container_name: summers_api_local_postgres
    volumes:
      - summers_api_local_postgres_data:/var/lib/postgresql/data:Z
      - summers_api_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: summers_api_local_redis

  celeryworker:
    <<: *django
    image: summers_api_local_celeryworker
    container_name: summers_api_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
