# Generated by Django 4.0.1 on 2022-02-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
