# Generated by Django 4.0.1 on 2022-03-07 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trakt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersshow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersshow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='categories',
            field=models.ManyToManyField(blank=True, to='trakt.Category'),
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trakt.show'),
        ),
    ]
