# Generated by Django 4.0.1 on 2022-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube2drive', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadrequest',
            options={'ordering': ['-updated_at'], 'verbose_name': 'UploadRequest', 'verbose_name_plural': 'UploadRequests'},
        ),
        migrations.AlterField(
            model_name='uploadrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FOLDER_NOT_FOUND_CHOICE', 'FOLDER_NOT_FOUND_CHOICE'), ('PLAYLIST_NOT_FOUND_CHOICE', 'PLAYLIST_NOT_FOUND_CHOICE')], default='START', max_length=25),
        ),
    ]
